// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARW_vt5tGLaXJ8KX_a39Cl_Ik3oosXTeg',
    appId: '1:228446276359:web:2edd391ebb4d04983e93a2',
    messagingSenderId: '228446276359',
    projectId: 'student-app-3cdff',
    authDomain: 'student-app-3cdff.firebaseapp.com',
    storageBucket: 'student-app-3cdff.appspot.com',
    measurementId: 'G-5MT7KF4DN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjrTxM4BswZgPA8pRK1hgQqICdgnNtGjs',
    appId: '1:228446276359:android:d5c80d33b41df3b63e93a2',
    messagingSenderId: '228446276359',
    projectId: 'student-app-3cdff',
    storageBucket: 'student-app-3cdff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgSLgu1D1GB_OmI5km0tg0m97HdDwqPNs',
    appId: '1:228446276359:ios:63b97afd47c483e73e93a2',
    messagingSenderId: '228446276359',
    projectId: 'student-app-3cdff',
    storageBucket: 'student-app-3cdff.appspot.com',
    iosBundleId: 'com.example.studentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgSLgu1D1GB_OmI5km0tg0m97HdDwqPNs',
    appId: '1:228446276359:ios:bcd2de87d0de37ff3e93a2',
    messagingSenderId: '228446276359',
    projectId: 'student-app-3cdff',
    storageBucket: 'student-app-3cdff.appspot.com',
    iosBundleId: 'com.example.studentapp.RunnerTests',
  );
}
